### ISSUE TITLE
getCurrentPosition() and watchPosition() are deprecated on insecure origins.

### ISSUE THREAD

**Issue by wokster** [BlueBiteLLC/service-geolocate-lite-js#3]
> getCurrentPosition() and watchPosition() are deprecated on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

can you fix it?

**Comment by matt-oconnell** [comment]
Unfortunately this is due to a change in Chrome's geolocation API where they have recently limited geolocation to 'only be accessible on "secure origins" (such as HTTPS.)' See: [Link](https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins).

The only way around this is to host a site on `https` or run chrome with flags (i.e. `chrome --unsafely-treat-insecure-origin-as-secure="http://example.com"`)

I'll add a note about this in the docs.
